# Generated by Django 4.2.29 on 2026-03-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservationApp", "0005_alter_booking_seats_alter_booking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="seats",
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
