# Generated by Django 4.2.29 on 2026-03-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservationApp", "0006_alter_bus_seats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="seats",
            field=models.IntegerField(default=0),
        ),
    ]
